spring:
  application:
    name: service-auth

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oauth_demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: root
      password: Passw0rd

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  redis:
#    host: 172.16.10.43
#    database: 1


server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging.level.org.springframework.security: DEBUG

